hermesEnabled=true
VisionCamera_enableCodeScanner=true
newArchEnabled=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
android.builtInKotlin=false
android.newDsl=false

MYAPP_UPLOAD_STORE_FILE=release-key.jks
MYAPP_UPLOAD_KEY_ALIAS=release-key
MYAPP_UPLOAD_STORE_PASSWORD=Snipsorfield
MYAPP_UPLOAD_KEY_PASSWORD=Snipsorfield