import React, {useState} from 'react';
import {Image, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, View} from 'react-native';
const emptyIcon = require('../../../assets/icons/employees-empty-state.png');
const ROLES = ['Owner', 'Employee'];
const GENDERS = ['Male', 'Female'];
const Chevron = ({open}) => <View style={[s.chevron, open && s.chevronOpen]} />;

function EmployeesScreen({initialEmployees = [], onBack, onSaveContinue}) {
  const [employees, setEmployees] = useState(initialEmployees);
  const [open, setOpen] = useState(false);
  const [phone, setPhone] = useState(''); const [first, setFirst] = useState(''); const [last, setLast] = useState('');
  const [role, setRole] = useState(''); const [gender, setGender] = useState(''); const [otp, setOtp] = useState('');
  const [otpSent, setOtpSent] = useState(false); const [verified, setVerified] = useState(false);
  const [roleOpen, setRoleOpen] = useState(false); const [genderOpen, setGenderOpen] = useState(false);
  const openForm = () => {setPhone('');setFirst('');setLast('');setRole('');setGender('');setOtp('');setOtpSent(false);setVerified(false);setRoleOpen(false);setGenderOpen(false);setOpen(true);};
  const canSave = verified && first.trim() && last.trim() && role && gender;
  const save = () => {if (!canSave) return; setEmployees(v => [...v, {id:String(Date.now()), phone, first:first.trim(), last:last.trim(), role, gender}]); setOpen(false);};
  return <SafeAreaView style={s.screen}>
    <StatusBar barStyle="light-content" backgroundColor="#07113D" />
    <View style={s.header}><Pressable onPress={onBack} style={s.back}><Text style={s.backText}>‹</Text></Pressable><Text style={s.headerTitle}>Employees</Text></View>
    <View style={s.progress}><Text style={s.step}>Step 5 of 8</Text><View style={s.track}><View style={s.fill} /></View></View>
    {!open && <View style={s.card}>{!employees.length ? <><View style={s.empty}><Image source={emptyIcon} resizeMode="contain" style={s.icon} /><Text style={s.emptyTitle}>No employees added yet</Text><Text style={s.desc}>Tap the button below to add{`\n`}your first employee.</Text></View><Pressable onPress={openForm} style={s.add}><Text style={s.plus}>＋</Text><Text style={s.addText}>Add employee</Text></Pressable></> : <><Text style={s.listTitle}>Employees added</Text><ScrollView>{employees.map(e => <View key={e.id} style={s.employee}><View style={s.avatar}><Text style={s.avatarText}>{e.first[0]}{e.last[0]}</Text></View><View style={s.employeeCopy}><Text style={s.name}>{e.first} {e.last}</Text><Text style={s.meta}>{e.role}</Text></View><View style={s.right}><Text style={s.phone}>{e.phone}</Text><Text style={s.meta}>{e.gender}</Text></View></View>)}</ScrollView><Pressable onPress={openForm} style={s.addMore}><Text style={s.plus}>＋</Text><Text style={s.addText}>Add more employees</Text></Pressable><View style={s.footer}><Pressable onPress={onBack} style={s.cancel}><Text style={s.cancelText}>Cancel</Text></Pressable><Pressable onPress={() => onSaveContinue?.(employees)} style={s.primary}><Text style={s.primaryText}>Save &amp; Continue</Text></Pressable></View></>}
    </View>}
    {open && <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={s.formScreen}><View style={s.sheet}><View style={s.sheetHead}><Text style={s.sheetTitle}>Add employee</Text><Pressable hitSlop={10} onPress={() => setOpen(false)}><Text style={s.close}>×</Text></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.form} showsVerticalScrollIndicator={false}>
      <Text style={s.label}>Phone Number *</Text><View style={s.phoneRow}><View style={s.code}><Text style={s.codeText}>+91</Text><View style={s.codeChevron}><Chevron /></View></View><TextInput editable={!verified} keyboardType="number-pad" maxLength={10} value={phone} onChangeText={v => {setPhone(v.replace(/\D/g,''));setOtpSent(false);setVerified(false);}} placeholder="Enter phone number" placeholderTextColor="#9AA2B5" style={[s.input,s.phoneInput]} /><Pressable disabled={phone.length !== 10 || verified} onPress={() => {setOtp('');setOtpSent(true);}} style={[s.send, (phone.length !== 10 || verified) && s.faded]}><Text style={[s.sendText,verified && s.green]}>{verified?'Verified':otpSent?'Sent':'Send OTP'}</Text></Pressable></View>
      {otpSent && <><Text style={s.label}>Enter OTP *</Text><View style={s.phoneRow}><TextInput keyboardType="number-pad" maxLength={6} value={otp} onChangeText={v => setOtp(v.replace(/\D/g,''))} placeholder="Enter OTP" placeholderTextColor="#9AA2B5" style={[s.input,s.phoneInput]} /><Pressable disabled={otp.length < 4} onPress={() => {setVerified(true);setOtpSent(false);setOtp('');}} style={[s.verify,otp.length < 4 && s.disabled]}><Text style={s.primaryText}>Verify</Text></Pressable></View></>}
      <Text style={s.label}>First Name *</Text><TextInput value={first} onChangeText={setFirst} placeholder="Enter first name" placeholderTextColor="#9AA2B5" style={s.input} />
      <Text style={s.label}>Last Name *</Text><TextInput value={last} onChangeText={setLast} placeholder="Enter last name" placeholderTextColor="#9AA2B5" style={s.input} />
      <Dropdown label="Role *" value={role} placeholder="Select role" items={ROLES} open={roleOpen} toggle={() => {setRoleOpen(v=>!v);setGenderOpen(false);}} select={v => {setRole(v);setRoleOpen(false);}} />
      <Dropdown label="Gender *" value={gender} placeholder="Select gender" items={GENDERS} open={genderOpen} toggle={() => {setGenderOpen(v=>!v);setRoleOpen(false);}} select={v => {setGender(v);setGenderOpen(false);}} />
      {verified && <View style={s.info}><Text style={s.infoIcon}>ⓘ</Text><Text style={s.infoText}>Employee can log in with this mobile number.</Text></View>}
    </ScrollView><View style={s.sheetFooter}><Pressable onPress={() => setOpen(false)} style={s.cancel}><Text style={s.cancelText}>Cancel</Text></Pressable><Pressable disabled={!canSave} onPress={save} style={[s.primary,!canSave&&s.disabled]}><Text style={s.primaryText}>Save</Text></Pressable></View></View></KeyboardAvoidingView>}
  </SafeAreaView>;
}
function Dropdown({label,value,placeholder,items,open,toggle,select}) {return <View><Text style={s.label}>{label}</Text><Pressable onPress={toggle} style={s.select}><Text style={[s.inputText,!value&&s.placeholder]}>{value||placeholder}</Text><Chevron open={open}/></Pressable>{open&&<View style={s.options}>{items.map(x=><Pressable key={x} onPress={()=>select(x)} style={s.option}><Text style={s.inputText}>{x}</Text>{value===x&&<Text style={s.check}>✓</Text>}</Pressable>)}</View>}</View>;}

const s=StyleSheet.create({
screen:{flex:1,backgroundColor:'#F7F8FC'},header:{height:55,backgroundColor:'#07113D',flexDirection:'row',alignItems:'center',paddingHorizontal:14},back:{width:34},backText:{color:'#FFF',fontSize:33},headerTitle:{color:'#FFF',fontSize:17,fontWeight:'600'},progress:{backgroundColor:'#07113D',paddingHorizontal:20,paddingBottom:15},step:{color:'#FFF',fontSize:13,marginBottom:9},track:{height:6,borderRadius:4,backgroundColor:'#61749C',overflow:'hidden'},fill:{width:'62.5%',height:'100%',backgroundColor:'#91B8F4'},card:{flex:1,marginHorizontal:8,marginBottom:10,padding:16,borderWidth:1,borderColor:'#E5E8EF',borderRadius:20,backgroundColor:'#FFF',elevation:2},empty:{alignItems:'center',marginTop:'30%'},icon:{width:116,height:116},emptyTitle:{marginTop:16,color:'#101735',fontSize:14,fontWeight:'700'},desc:{marginTop:10,color:'#3E4A6A',fontSize:11,lineHeight:18,textAlign:'center'},add:{height:46,marginTop:74,borderWidth:1.2,borderColor:'#243B75',borderRadius:6,flexDirection:'row',alignItems:'center',justifyContent:'center'},plus:{marginRight:9,color:'#1D356E',fontSize:20},addText:{color:'#172B61',fontSize:12,fontWeight:'600'},listTitle:{fontSize:15,fontWeight:'700',color:'#17203B',marginBottom:14},employee:{height:72,borderWidth:1,borderColor:'#E3E7EF',borderRadius:7,padding:8,flexDirection:'row',alignItems:'center'},avatar:{width:43,height:43,borderRadius:22,backgroundColor:'#F0F2F8',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:12,color:'#24345F'},employeeCopy:{flex:1,marginLeft:10},name:{fontSize:11,color:'#17203B',fontWeight:'700'},meta:{fontSize:9,color:'#334A85',marginTop:5},right:{alignItems:'flex-end'},phone:{fontSize:9,color:'#17203B'},addMore:{height:46,borderWidth:1.2,borderColor:'#243B75',borderRadius:6,flexDirection:'row',alignItems:'center',justifyContent:'center'},footer:{flexDirection:'row',gap:10,marginTop:22},cancel:{flex:1,height:44,borderWidth:1,borderColor:'#284A8F',borderRadius:6,alignItems:'center',justifyContent:'center'},cancelText:{fontSize:12,color:'#17346F',fontWeight:'600'},primary:{flex:1.1,height:44,borderRadius:6,backgroundColor:'#07113D',alignItems:'center',justifyContent:'center'},primaryText:{fontSize:11,color:'#FFF',fontWeight:'600'},
formScreen:{flex:1,backgroundColor:'#FFF'},sheet:{flex:1,backgroundColor:'#FFF',paddingHorizontal:22,paddingTop:8,paddingBottom:14},sheetHead:{height:50,marginBottom:2,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},sheetTitle:{fontSize:17,fontWeight:'600',color:'#17203B'},close:{fontSize:27,color:'#17203B'},form:{paddingBottom:18},label:{fontSize:10,fontWeight:'600',color:'#1D2744',marginTop:15,marginBottom:7},input:{height:40,borderWidth:1,borderColor:'#DCE1EA',borderRadius:6,paddingHorizontal:10,color:'#202A47',fontSize:11},phoneRow:{flexDirection:'row',gap:7,alignItems:'center'},code:{width:56,height:40,borderWidth:1,borderColor:'#DCE1EA',borderRadius:6,paddingLeft:9,paddingRight:8,flexDirection:'row',alignItems:'center'},codeText:{fontSize:11,color:'#202A47',marginRight:8},codeChevron:{marginLeft:'auto',paddingTop:3},inputText:{fontSize:11,color:'#202A47'},phoneInput:{flex:1},send:{width:65,height:40,borderWidth:1,borderColor:'#9DA9C0',borderRadius:6,alignItems:'center',justifyContent:'center'},sendText:{fontSize:9,color:'#172B61',fontWeight:'600'},green:{color:'#218457'},faded:{opacity:.55},verify:{width:72,height:40,borderRadius:6,backgroundColor:'#07113D',alignItems:'center',justifyContent:'center'},disabled:{backgroundColor:'#9BA5B8'},select:{height:40,borderWidth:1,borderColor:'#DCE1EA',borderRadius:6,paddingHorizontal:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},placeholder:{color:'#9AA2B5'},chevron:{width:7,height:7,marginTop:-4,borderRightWidth:1.2,borderBottomWidth:1.2,borderColor:'#43577D',transform:[{rotate:'45deg'}]},chevronOpen:{marginTop:4,transform:[{rotate:'225deg'}]},options:{borderWidth:1,borderColor:'#DCE1EA',borderRadius:6,backgroundColor:'#FFF',marginTop:3},option:{height:38,paddingHorizontal:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#EDF0F4'},check:{color:'#25478C'},info:{marginTop:14,padding:9,borderRadius:6,backgroundColor:'#F2F4F8',flexDirection:'row'},infoIcon:{color:'#304D89',marginRight:7},infoText:{fontSize:9,color:'#52607B'},sheetFooter:{paddingTop:12,borderTopWidth:1,borderTopColor:'#ECEEF3',flexDirection:'row',gap:10}
});
export default EmployeesScreen;
