import React from 'react';
import {Image,Pressable,SafeAreaView,StatusBar,StyleSheet,Text,View} from 'react-native';

const STATUS_ICONS={submitted:require('../../../assets/icons/onboarding-submitted.png'),pending:require('../../../assets/icons/kyc-pending.png'),rejected:require('../../../assets/icons/kyc-rejected.png')};

const COPY={submitted:{header:'Onboarding Submitted',title:'Onboarding Submitted!',message:'Thank you! Your salon has been submitted successfully.',color:'#12A85A',symbol:'✓'},pending:{header:'KYC Pending',title:'Under Verification',message:"Your KYC details are under verification.\nWe'll notify you once it's approved.",color:'#FF9818',symbol:'◷'},rejected:{header:'KYC Rejected',title:'Rejected',message:'Your KYC submission has been rejected.\nPlease fix the issues and resubmit.',color:'#E53935',symbol:'×'}};
function OnboardingStatusScreen({status='submitted',salon,onBack,onViewKyc,onFixKyc}){const c=COPY[status]||COPY.submitted;return <SafeAreaView style={s.screen}><StatusBar barStyle="light-content" backgroundColor="#07113D"/><View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>‹</Text></Pressable><Text style={s.headerText}>{c.header}</Text></View><View style={s.body}><Image source={STATUS_ICONS[status]||STATUS_ICONS.submitted} resizeMode="contain" style={s.statusIcon}/><Text style={s.title}>{c.title}</Text><Text style={s.message}>{c.message}</Text>{status==='pending'&&<View style={s.details}><Row a="Salon Name" b={salon?.name||'Salon'}/><Row a="Submitted On" b="Just now"/><Row a="Expected Status" b="Within 24–48 Hours"/></View>}{status==='rejected'&&<View style={s.reject}><Text style={s.rejectTitle}>Reason for Rejection</Text><Text style={s.rejectText}>IFSC code is invalid. Please provide a valid IFSC code for the bank account.</Text><Row a="Submitted On" b="Recently"/><Row a="Rejected On" b="Just now"/></View>}<View style={s.actions}>{status==='rejected'?<><Pressable onPress={onFixKyc} style={s.primary}><Text style={s.primaryText}>Fix KYC Details</Text></Pressable><Pressable onPress={onViewKyc} style={s.secondary}><Text style={s.secondaryText}>View KYC Details</Text></Pressable></>:status==='pending'?<><Pressable onPress={onViewKyc} style={s.primary}><Text style={s.primaryText}>View KYC Details</Text></Pressable><Pressable onPress={onBack} style={s.secondary}><Text style={s.secondaryText}>Back to Salons</Text></Pressable></>:<Pressable onPress={onBack} style={s.primary}><Text style={s.primaryText}>Back to Salons</Text></Pressable>}</View></View></SafeAreaView>;}
const Row=({a,b})=><View style={s.row}><Text style={s.rowA}>{a}</Text><Text style={s.rowB}>{b}</Text></View>;
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#FFF'},header:{height:58,paddingHorizontal:16,backgroundColor:'#07113D',flexDirection:'row',alignItems:'center'},back:{fontSize:34,color:'#FFF',marginRight:18},headerText:{fontSize:17,color:'#FFF',fontWeight:'600'},body:{flex:1,padding:20,alignItems:'center'},statusIcon:{width:126,height:126,marginTop:16},title:{fontSize:19,color:'#18213E',fontWeight:'700',marginTop:12},message:{fontSize:11,lineHeight:18,color:'#53607B',fontWeight:'600',textAlign:'center',marginTop:10},details:{width:'100%',marginTop:34,padding:14,borderRadius:9,backgroundColor:'#FFF7EC',borderWidth:1,borderColor:'#F5DDBB'},reject:{width:'100%',marginTop:28,padding:14,borderRadius:9,backgroundColor:'#FFF0F0',borderWidth:1,borderColor:'#F2BFC0'},rejectTitle:{fontSize:12,color:'#A42327',fontWeight:'700'},rejectText:{fontSize:10,lineHeight:17,color:'#9A3438',fontWeight:'600',marginTop:8,marginBottom:8},row:{minHeight:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'rgba(80,80,80,.12)'},rowA:{fontSize:10,color:'#34425F',fontWeight:'600'},rowB:{fontSize:10,color:'#253655',fontWeight:'700'},actions:{width:'100%',marginTop:'auto',gap:10},primary:{height:46,borderRadius:6,backgroundColor:'#07113D',alignItems:'center',justifyContent:'center'},primaryText:{fontSize:12,color:'#FFF',fontWeight:'700'},secondary:{height:44,borderWidth:1,borderColor:'#36548E',borderRadius:6,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:12,color:'#213A70',fontWeight:'700'}});
export default OnboardingStatusScreen;
